WorldHub: Make worlds directory path configurable
bridge-core/plugins pull request #114
Opened 2022-04-24 09:18 UTC by aexer0e

# WorldHub: Configurable Worlds Directory Path

Added support for setting the directory path WorldHub tries to fetch worlds from within the project's `config.json` so that we're no longer constricted to just "worlds/". 

## Usage
To set a custom directory path, add a `"WorldHub"` entry in `config.json`, within which set the `"dirPath"` key to the value of your custom worlds directory, like so:
```
{
    "WorldHub": {
        "dirPath": "my-worlds"
    }
}
```

## Backwards Compatibility
When un-set, WorldHub will default to using "worlds".

2022-04-24 09:48 UTC, solvedDev commented
Some functionality inside of bridge. (e.g. packaging) currently still relies on the "worlds/" folder (See #389). Since we've seen the need to customize the folder, we've already engaged on the project config standard to add a new "worlds" property to the config file: https://github.com/Bedrock-OSS/project-config-standard/issues/2

I am open to merge the PR for now though

2022-04-24 15:36 UTC, aexer0e commented
I see. I think the standardized "worlds" property within a project's config should be implemented and parsed within dash itself and be available for extensions/custom compilers as a hook since it's fairly sophisticated and that way 3rd party utilizations won't have to worry about how to go about parsing project worlds, but until then I think this is a good compromise and it wouldn't be harmful if a standardization is implemented at a lower level in the future.

2022-04-25 10:33 UTC, solvedDev commented
> I think the standardized "worlds" property within a project's config should be implemented and parsed within dash or bridge.?

Yes, this parsing of this property is already implemented for a couple of bridge. versions and can be accessed over the project config module. (There's a new, undocumented `config.getWorldHandles(): Promise<FileSystemDirectoryHandle[]>` method on the ProjectConfig class)

2022-04-25 10:36 UTC, solvedDev requested changes
Generally looks good to me. Please adjust the property name and then this should be ready to merge

2022-04-25 10:36 UTC, solvedDev commented on plugins/WorldHub/scripts/worldHub.js
> +	worldsDir = Config?.WorldHub?.dirPath || 'worlds'
I would prefer the "WorldHub" namespace property to start with a lowercase letter to align it with the other properties within the project config -> Use "worldHub" instead

2022-04-25 10:49 UTC, solvedDev approved these changes
LGTM

2022-04-25 10:49 UTC, merged