Added 4 Modern Themes That Use CSS To Make A Gradient Background
bridge-core/plugins pull request #52
Opened 2021-05-25 16:14 UTC by outercloudstudio

2021-05-25 16:49 UTC, outercloudstudio commented
I removed the end and nether themes because they were not good enough.

2021-05-25 21:59 UTC, outercloudstudio commented
Also I added 4 modern themes that I think look really cool.

2021-05-26 08:45 UTC, solvedDev requested changes

2021-05-26 08:45 UTC, solvedDev commented on plugins/ModernTheme/manifest.json
> +	"description": "Adds multiple asthetic modern themes to select in File > Prefrences > Setting > Apearence!",
Typo: "Prefrences"

2021-05-26 18:44 UTC, outercloudstudio commented
The typo should be fixed now.

2021-05-26 18:59 UTC, solvedDev approved these changes

2021-05-26 18:59 UTC, merged